# Generated by Django 5.2.16 on 2026-07-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', editable=False, max_length=201),
            preserve_default=False,
        ),
    ]
